### PR TITLE
CI: integration test

### PR DESCRIPTION
**Pull request by fzzr-**
- added rustfmt check
- refactored `cargo test` job
- added integration test

Integration tests with crankstart:
- [x] macOS: OK
- [ ] linux: CI is OK, Crank seems broken
- [ ] windows: I don't know how to install SDK

- - -

On linux SDK installed normally.
Crank fails with [that][]:
```
INFO  crank > make_source_dir
 INFO  crank > link_dylib
 DEBUG crank > copy: "/home/runner/work/crank-1/crank-1/crankstart/target/release/examples/libhello_world.dylib" -> "/home/runner/work/crank-1/crank-1/crankstart/target/Hello World/pdex.dylib"
Error: No such file or directory (os error 2)
```

[that]: https://github.com/fzzr-/crank-1/runs/5589357742?check_suite_focus=true

### CODE REVIEW

**Comment by rtsuk** [comment]
It's weird that it's making a dylib on Linux. I confess I've not used the Linux support much, if at all.

**Comment by fzzr-** [comment]
> This workflow is awaiting approval from a maintainer in https://github.com/rtsuk/crank/pull/10

**Comment by fzzr-** [comment]
There's no `dylib`, just `a` and `so`.

Screenshot 2022-03-18 at 14 55 54

**Comment by rtsuk** [comment]
Oh, I see, the verbose printing is wrong.

**Comment by fzzr-** [comment]
I'm not sure but seems to.

**Comment by rtsuk** [comment]
It appears that https://github.com/rtsuk/crank/blob/main/src/main.rs#L425 needs to be broken out into linux and macOS. I don't have a linux setup right now. I'd be fine with disabling Linux and adding an issue to fix it, which hopefully a linux user can take on.

**Comment by fzzr-** [comment]
Fixed. But currently I cannot test __run in sim__ on linux.
Actual questions:
- Is there any way to __validate__ resulting package `.pdx`?
    - I'm not sure is there should be lib named as `pdex.so` or `pdex.dylib` in the package.

**Comment by fzzr-** [comment]
I'm played with it. See https://github.com/fzzr-/crank-1/pull/4/files#diff-42cb6807ad74b3e201c5a7ca98b911c5fa08380e942be6e4ac5807f8377f87fcR421-R424

**Comment by fzzr-** [comment]
>  I'd be fine with disabling Linux and adding an issue to fix it

Okay. I'll just comment the linux option in the job-matrix as same as windows already.
Could you create issues please?

**Comment by fzzr-** [comment]
Also, again
> This workflow is awaiting approval from a maintainer in https://github.com/rtsuk/crank/pull/10

**Comment by fzzr-** [comment]
Todo issues:
- CI: fix SDK installation on windows
- Crank: fix and test package build for linux
- Crank: test package build for linux

**Comment by fzzr-** [comment]
I think this PR is ready.
- linux & windows jobs disabled for integration tests, enabled for build and unit-tests
- fixed rustfmt job, fixed code formatting (one line :) )
- fixed dylib/so packaging for linux

**Pull request merged**
